### ISSUE TITLE
Startup error on 1.16.2 server on latest Fabric.

### ISSUE THREAD

**Issue by xDraxxis** [LolHens/dynmap-fabric#17] opened 2020-08-14 05:59 UTC
```
[07:54:55] [Dynmap Render Thread/FATAL]: [Dynmap] Exception while loading chunks
java.lang.NullPointerException: null
at net.minecraft.class_2852.method_12385(class_2852.java:413) ~[intermediary-server.jar:?]
at net.minecraft.class_2852.method_12410(class_2852.java:359) ~[intermediary-server.jar:?]
at org.dynmap.fabric_1_16_2.FabricMapChunkCache.getLoadedChunks(FabricMapChunkCache.java:1100) ~[dynmap-fabric-0.2.7+1.16.2.jar:?]
at org.dynmap.fabric_1_16_2.FabricServer$1.call(FabricServer.java:425) ~[dynmap-fabric-0.2.7+1.16.2.jar:?]
at org.dynmap.fabric_1_16_2.FabricServer$1.call(FabricServer.java:419) ~[dynmap-fabric-0.2.7+1.16.2.jar:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
at org.dynmap.fabric_1_16_2.TaskRecord.run(TaskRecord.java:17) ~[dynmap-fabric-0.2.7+1.16.2.jar:?]
at org.dynmap.fabric_1_16_2.FabricServer.tickEvent(FabricServer.java:499) ~[dynmap-fabric-0.2.7+1.16.2.jar:?]
at org.dynmap.fabric_1_16_2.DynmapPlugin.lambda$onStart$0(DynmapPlugin.java:503) ~[dynmap-fabric-0.2.7+1.16.2.jar:?]
at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$null$2(ServerTickEvents.java:62) ~[b80b4d6d-5e41-4ee6-8aae-16f1731761e4.jar:?]
at net.minecraft.server.MinecraftServer.handler$zze000$onEndTick(MinecraftServer.java:1750) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:850) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.handler$zig000$modifiedRunLoop(MinecraftServer.java:3797) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:648) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by lhns** [comment] 2020-08-14 08:13
Are you running this on a dedicated server or client?
I also had this happen once but couldn't reproduce it.

For now I built a workaround in 1e767984ab51f82be06888aaf0afc1ee4b4ed056 that will show the exception in the console but don't crash the game.

**Comment by xDraxxis** [comment] 2020-08-14 16:01
It's on a server, however im also having issues with chunk saving at the moment, so that could be causing this issue

**Comment by lhns** [comment] 2020-08-16 12:57
I will close this for now. If you still have this issue feel free to comment below and I will reopen.

**Closed as completed by lhns** 2020-08-16 12:57 UTC
Labels: bug
