### ISSUE TITLE
Crash with Dynmap 1.16.1

### ISSUE THREAD

**Issue by shueja** [LolHens/dynmap-fabric#16] opened 2020-08-14 03:06 UTC
https://paste.ee/p/hF6GT is the crash report
![image](https://user-images.githubusercontent.com/32416547/90209476-5fcd0900-dda0-11ea-8ead-a7dfb44e1d68.png)
I'm not sure what other information is necessary.

**Comment by lhns** [comment] 2020-08-14 08:10
I think the issue is that your fabric-api is too old. I will set a minimum fabric version then fabric will show an error message.

**Comment by lhns** [comment] 2020-08-14 08:48
fixed by 01648d9e04c670fe51b89b294e192d226b2d8015

**Comment by lhns** [comment] 2020-08-14 08:50
fixed in 0.2.8+1.16.1

**Closed as completed by lhns** 2020-08-14 08:50 UTC
Labels: enhancement
